### PR TITLE
Add wazero user: wescale

### PR DESCRIPTION
**Pull request by earayu**

### CODE REVIEW

**Comment by evacchi** [comment]
make sure to sign the DCO, [see the instructions here](https://github.com/tetratelabs/wazero/pull/2239/checks?check_run_id=25972024592)

**Comment by mathetake** [comment]
Mind fixing the DCO?

**Comment by evacchi** [comment]
@earayu you should update the DCO, otherwise we can't merge! :)

**Comment by earayu** [comment]
> @earayu you should update the DCO, otherwise we can't merge! :)

Ok, I'll do it.

**Comment by earayu** [comment]
> make sure to sign the DCO, [see the instructions here](https://github.com/tetratelabs/wazero/pull/2239/checks?check_run_id=25972024592)

fixed

**Pull request merged**
