### PR TITLE
Fix path to spec tests

### LINKED ISSUE #247: Spec tests are skipped
Spec tests are skipped because wrong directory (`.` instead of `testdata`)
image

### PR DESCRIPTION
**Pull request by r8d8**
Fix #247

### CODE REVIEW

**Comment by r8d8** [comment]
Test interpreter failing on Risc-V
```
--- FAIL: TestInterpreter (26.31s)
    --- FAIL: TestInterpreter/f32_bitwise.wast (0.07s)
        --- FAIL: TestInterpreter/f32_bitwise.wast/assert_return/line:78 (0.00s)
            spec_test.go:427: 
                    Error Trace:    spec_test.go:427
                                                spec_test.go:296
                    Error:          Not equal: 
                                    expected: -1e-45
                                    actual  : 1e-45
                    Test:           TestInterpreter/f32_bitwise.wast/assert_return/line:78
                    Messages:       f32_bitwise.wast:78 assert_return invoke copysign ([{type: f32, value: -0.000000} {type: f32, value: NaN}])
...
```

**Comment by codefromthecrypt** [comment]
Thanks! any ideas how we ended up with green builds before this? we should fix CI also to prevent false positives..

**Comment by mathetake** [comment]
so i pushed a commit to prevent false-positive and stop testing risc-v for now.

**Review by mathetake — APPROVED** [review]

**Comment by mathetake** [comment]
@r8d8 thank you for finding this out!! It are really helping us! 💯 🏅

**Pull request merged**
