### PR TITLE
internal: some WIP on being able to compile wazero for MCUs using TinyGo

### PR DESCRIPTION
**Pull request by deadprogram**
This PR is a place for some WIP on getting wazero to compile with TinyGo so it can be run on microcontrollers.

See #1854 for details.

This is as far as I have been able to get this far with the code in this PR:

```
$ tinygo build -o basic.uf2 -target=itsybitsy-m4 -tags=tinygo ./examples/basic/
# github.com/tetratelabs/wazero/internal/sock
internal/sock/sock.go:66:59: undefined: net.TCPListener
internal/sock/sock_supported.go:8:22: undefined: syscall.SHUT_RD
internal/sock/sock_supported.go:9:22: undefined: syscall.SHUT_RDWR
internal/sock/sock_supported.go:10:22: undefined: syscall.SHUT_WR
internal/sock/sock.go:73:28: undefined: net.TCPListener
```

### CODE REVIEW

**Comment by deadprogram** [comment]
Now that I look bit deeper, the bigger problem is likely to be not being able to generate the needed code for the target itself that it would be running on: https://github.com/tetratelabs/wazero/tree/main/internal/asm

This is not a small task.

**Comment by ncruces** [comment]
Is an interpreter not useful at all?

**Comment by deadprogram** [comment]
> Is an interpreter not useful at all?

I would be happy to get interpreter working, but not sure that will work either due to instruction set of target being `ARMv7-M Thumb`

**Comment by evacchi** [comment]
the interpreter should work regardless. You can compile wazero today to wasm with `GOOS=wasip1 GOARCH=wasm` and it will build the interpreter.

**Comment by deadprogram** [comment]
> the interpreter should work regardless.

OK, good to know. I will continue playing with it this weekend.

**Comment by deadprogram** [comment]
A couple fixes from @aykevl and I was able to at least compile:

```
$ tinygo build -size short -o wazero-micro.uf2 -target itsybitsy-m4 -stack-size 8kb -tags tinygo ./examples/basic/
   code    data     bss |   flash     ram
 375788   72072   18544 |  447860   90616
```

Now to start getting things to work!

**Comment by evacchi** [comment]
Nice!

**Comment by evacchi** [comment]
nice to see further progress here!

**Comment by evacchi** [comment]
should we close this one?

**Comment by deadprogram** [comment]
Closing in favor of the @orsinium collection of PRs.

**Pull request closed without merging**
