### PR TITLE
threads: add function validation of atomics

### PR DESCRIPTION
**Pull request by anuraaga**

### CODE REVIEW

**Review by mathetake — APPROVED** [review]
I slightly remember that memory must have min==max, but where is it validated?

**Comment by anuraaga** [comment]
@mathetake Hmm, don't think I've seen that anywhere. For example in libpgquery wasm, memory looks like this

`(memory (;0;) 15 65536 shared)`

**Comment by mathetake** [comment]
aha ok

**Comment by mathetake** [comment]
then what happens when growing memory (changing the base address would be dangerous I guess when multiple threads are executing load/store?)

**Comment by anuraaga** [comment]
@mathetake Yup you're right. We discussed a bit but basically the only way to support it, without allocating tons of memory up front, is to use mmap. I think I need to clean up the implementation a bit before sending the PR for here, but currently it looks like this

https://github.com/wasilibs/wazerox/blob/main/internal/wasm/memory.go#L74

Will it be ok?

**Comment by mathetake** [comment]
yeah looks good provided the behavior is well-documented on the API to toggle threads instructions. IIRC mmap itself doesn't immediately allocate physical pages immediately so it makes sense

**Comment by ncruces** [comment]
I wonder, do tests pass on 32-bit platforms, with mmaping 65536 pages (4GB)?

**Pull request merged**
