### PR TITLE
fuzz: don't use rust nightly

### PR DESCRIPTION
**Pull request by anuraaga**

### CODE REVIEW

**Comment by anuraaga** [comment]
Sorry I meant to open this on my fork but somehow it opened upstream. Let me close this if CI fails

**Review by mathetake — APPROVED** [review]
looks like it's working hah

**Review by mathetake — COMMENTED** [review]
well maybe it's already cached... could you try changing the cache key for testing?

**Comment by anuraaga** [comment]
@mathetake There's lots of output like this. Do you think it's still needed to verify with different cache?

```
INFO: Seed: 3180237802
INFO: Loaded 1 modules   (122050 inline 8-bit counters): 122050 [0x561ea2e5b458, 0x561ea2e7911a), 
INFO: Loaded 1 PC tables (122050 PCs): 122050 [0x561ea2e79120,0x561ea3055d40), 
INFO:     6931 files found in /home/runner/work/wazero/wazero/internal/integration_test/fuzz/fuzz/corpus/no_diff
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: seed corpus: files: 6931 min: 2b max: 373b total: 959366b rss: 44Mb
#2048	pulse  cov: 5945 ft: 18363 corp: 1765/135Kb exec/s: 1024 rss: 61Mb
#4096	pulse  cov: 7381 ft: 27037 corp: 3503/328Kb exec/s: 819 rss: 64Mb
#6932	INITED cov: 8122 ft: 38150 corp: 6024/819Kb exec/s: 577 rss: 66Mb
#7187	NEW    cov: 8122 ft: 38156 corp: 6025/819Kb lim: 381 exec/s: 598 rss: 66Mb L: 168/373 MS: 5 CMP-ChangeASCIIInt-CMP-CMP-ChangeBinInt- DE: "\007\000"-"\021\000"-"30"-
#7218	REDUCE cov: 8122 ft: 38156 corp: 6025/819Kb lim: 381 exec/s: 601 rss: 66Mb L: [113](https://github.com/tetratelabs/wazero/actions/runs/7633797120/job/20796684296?pr=1947#step:6:114)/373 MS: 1 EraseBytes-
#7453	NEW    cov: 8122 ft: 38162 corp: 6026/820Kb lim: 381 exec/s: 621 rss: 68Mb L: 186/373 MS: 5 InsertRepeatedBytes-ChangeASCIIInt-ChangeBit-ShuffleBytes-PersAutoDict- DE: "\007\000"-
#7756	NEW    cov: 8122 ft: 38164 corp: 6027/820Kb lim: 381 exec/s: 596 rss: 68Mb L: 339/373 MS: 3 ChangeByte-ChangeBit-InsertRepeatedBytes-
#7868	NEW    cov: 8122 ft: 38167 corp: 6028/820Kb lim: 381 exec/s: 605 rss: 68Mb L: 284/373 MS: 2 InsertRepeatedBytes-CMP- DE: "\011\000\000\000\000\000\000\000"-
```

**Comment by anuraaga** [comment]
Well why not, giving it a try with different cache key

**Review by mathetake — APPROVED** [review]

**Pull request merged**
