### PR TITLE
Remove threads support

### PR DESCRIPTION
**Pull request by anuraaga**
Spec is still not in a great state

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
considering the state of the threads proposal and the mosquito-bites of broken builds, hacks, and other cognitive load on various devs since this was merged...

I'm wondering if it we aren't digging a hole. Could it be better to revert it and try again later when things normalize? https://github.com/WebAssembly/threads/issues/198

**Comment by anuraaga** [comment]
Sure I think that makes sense too

**Comment by mathetake** [comment]
At least the state makes me feel like we should put on hold the implementation on compiler backend at least until it reaches the phrase 4.

**Comment by codefromthecrypt** [comment]
thanks folks. I think we learned a lot and will be better off on the redo. @anuraaga do you want to raise the revert (or re-purpose this one?)

**Comment by anuraaga** [comment]
Sure, repurposed this PR

**Review by codefromthecrypt — APPROVED** [review]
Thanks for the understanding @anuraaga!

**Review by mathetake — APPROVED** [review]
🫡 👍

**Pull request merged**
