### PR TITLE
Adds support for nontrapping float to int conversion proposal

### PR DESCRIPTION
**Pull request by mathetake**
This commit adds support for "nontrapping float to int conversion" proposal
which is one of the finished proposals at this point and is included in the 2.0 draft.

https://github.com/WebAssembly/spec/blob/main/proposals/nontrapping-float-to-int-conversion/Overview.md

### CODE REVIEW

**Comment by mathetake** [comment]
done with interpreter including test.. next is JIT!

**Comment by mathetake** [comment]
ok the left is arm64

**Comment by mathetake** [comment]
done (surprisingly only one line change was necessary:D)

**Comment by mathetake** [comment]
ok waiting for @codefromthecrypt to do post 1.0 spectest refactoring!

**Comment by codefromthecrypt** [comment]
on this now

**Review by codefromthecrypt — APPROVED** [review]
approve on the existing work. I'll  put the wazeroir and spectests in

**Comment by codefromthecrypt** [comment]
I'll start with adding ops into the text decoder so I can more easily backfill wazeroir tests.. if that becomes too tricky, I'll add wazeroir using manually generated wasm.

**Comment by codefromthecrypt** [comment]
@mathetake so i started the spec tests which fail on interpreter but pass on JIT. Also some comments/questions how to test the values not obviously representable in Go. Can you push a commit to fix the things and answer those? I'll continue after!

**Comment by mathetake** [comment]
Test fixed! On the comment about NaNs, there are not representative (as far as i know though) in Go, and so that's the reason why I added the perl magic in Makefile https://github.com/tetratelabs/wazero/blob/main/Makefile#L36-L40

**Comment by mathetake** [comment]
glad to know that now passes spectests 😄

**Comment by codefromthecrypt** [comment]
thanks for the help. I'll finish up the spectests!

**Comment by codefromthecrypt** [comment]
@mathetake done. merge when ready!

**Review by codefromthecrypt — APPROVED** [review]

**Pull request merged**
