### PR TITLE
ci: tests with Go 1.23rc2

### PR DESCRIPTION
**Pull request by mathetake**

### CODE REVIEW

**Comment by mathetake** [comment]
GOOS=wasip1 os package on Windows is failing 😉

**Comment by mathetake** [comment]
for the interpreter tests on RISCV64 - https://github.com/golang/go/issues/68322

**Comment by mathetake** [comment]
https://github.com/tetratelabs/wazero/issues/2280

**Comment by evacchi** [comment]
> @evacchi did it

😄

**Pull request merged**
