### PR TITLE
Redirects users to tested example

### PR DESCRIPTION
**Pull request by codefromthecrypt**
Rather than clutter both the README and home page with details that can
drift and have caused maintenance, this directs users to the tested
basic example.

This also adds a FAQ entry about TinyGo's main, thanks to @basvanbeek
for the help.

### CODE REVIEW

**Review by mathetake — COMMENTED** [review]
nit `examples/basic/testdata/add.wasm` is changed to 755 permission but do we need the execution bit?

**Review by mathetake — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
weird on chmod. fixed it!

**Comment by codefromthecrypt** [comment]
fyi https://deploy-preview-791--wazero.netlify.app/

**Comment by codefromthecrypt** [comment]
need to sort out the example test

**Pull request merged**
