### PR TITLE
fuzz: adds unaligned global f32 case

### PR DESCRIPTION
**Pull request by evacchi**
fails consistently on amd64, but it won't crash rosetta2 on macOS/Arm
EDIT: and unfortunately it's not crashing qemu either...

```
evacchi@lima-amd64:/Users/evacchi/Devel/github.com/tetratelabs/wazero/internal/integration_test/fuzzcases$ ./fuzz.test -test.v -test.run Test2040
=== RUN   Test2040
--- PASS: Test2040 (0.00s)
PASS
```

### CODE REVIEW

**Comment by mathetake** [comment]
Cool thanks... this is weird...

**Comment by mathetake** [comment]
I will take this from here. I managed to reproduce with EPYC-v3 CPU on qemu.

**Comment by evacchi** [comment]
oh cool!

**Comment by mathetake** [comment]
https://github.com/tetratelabs/wazero/pull/2042 temporarily allows passing this test case, but I will do the more fundamental fix later. anyway thank you for noticing this crash!

**Review by mathetake — APPROVED** [review]

**Pull request merged**
