### PR TITLE
Update TinyGo to 0.22.0

### PR DESCRIPTION
**Pull request by mathetake**
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

### CODE REVIEW

**Comment by mathetake** [comment]
huh looks like now tinygo's WASI target requires `clock_time_get` by default.. @nullpo-head could you implement `clock_time_get` after #166 ?

**Comment by nullpo-head** [comment]
>huh looks like now tinygo's WASI target requires clock_time_get by default.. nullpo-head could you implement clock_time_get after #166 ?


sure!

**Comment by tonyhb** [comment]
> huh looks like now tinygo's WASI target requires `clock_time_get` by default

Just started looking into this project - it's amazing!  Rust also requires `clock_time_get` for some projects, too.  Got that error just now!

**Comment by mathetake** [comment]
I think now this works!

**Review by codefromthecrypt — APPROVED** [review]
Besides the wasi things we ran into, anything notable trivia wrt wasm support on this one?

**Comment by mathetake** [comment]
nothing notable 😄

**Pull request merged**
