### PR TITLE
Fix fdPread: shouldn't move file offset

### LINKED ISSUE #958: WASI fd_pread incorrectly moves file offset
**Describe the bug**

The [`fd_pread`](https://github.com/WebAssembly/WASI/blob/snapshot-01/phases/snapshot/docs.md#-fd_preadfd-fd-iovs-iovec_array-offset-filesize---errno-size) WASI syscall incorrectly moves the file offset.

Implementation probably can't be shared with `fd_read`, and should use `io.ReaderAt` not `io.ReadSeeker`.
https://github.com/tetratelabs/wazero/blob/6b9d119a7b069561ccb7f536a6d0d97d3772f549/imports/wasi_snapshot_preview1/fs.go#L561-L624

**To Reproduce**

```sh
git clone https://github.com/ncruces/wazero-bugs.git
cd wazero-bugs

echo Expected output:
cc -o main main.c && ./main

echo Actual output:
go run ./cmd
```

**Expected behavior**

```
Expected output:
Line 1
Line 2
Line 1
Line 3
Actual output:
Line 1
Line 2
Line 1
Line 2
```

Note the difference in the last line.

**Environment (please complete the relevant information):**
- Go version: 1.19.4
- wazero Version: v1.0.0-pre.5
- Host architecture: amd64
- Runtime mode: compiler

**Additional context**

[`main.c`](https://github.com/ncruces/wazero-bugs/blob/main/main.c) and [`main.go`](https://github.com/ncruces/wazero-bugs/blob/main/cmd/main.go) should be pretty self explanatory.
`main.wasm` from the repo was compiled with `zig cc --target=wasm32-wasi` version `0.10.0`.

I tried running it with `wasmtime --dir . main.wasm` which produces the correct output.

### PR DESCRIPTION
**Pull request by ncruces**
Fixes #958.

This is breaking a zig test, I still haven't been able to figure out why.

### CODE REVIEW

**Comment by ncruces** [comment]
It seems, at the root of it, we have that [`embed.openfile`](https://github.com/golang/go/blob/15605ca827723d568f780402d03b29842fd20eec/src/embed/embed.go#L342-L350) does not implement `io.ReaderAt`. 😔

**Comment by ncruces** [comment]
I could `Seek`, `Read` and then `Seek` back. But if any operation fails, I'm breaking the invariant of `pread`: _“The file offset is not changed.”_

**Comment by codefromthecrypt** [comment]
@ncruces is it required for embed to implement this, or is it just due to our tests using embed?

**Comment by ncruces** [comment]
No, not required. It's just due to tests using embed.

But it also means anyone using embed will start seeing `pread` failures. And it seems zig uses `pread` for most (all?) reads.

I came up with an alternative implementation that tries `io.ReaderAt` and falls back to `io.Seeker` doing multiple seeks. All tests pass. https://github.com/ncruces/wazero/commit/e12b34e2e3e8ab9e3d09d5c59afd63c28198712f

There's some prior to doing this. For instance, see Go's implementation of `pread` under Windows:
https://github.com/golang/go/blob/e870de9936a7efa42ac1915ff4ffb16017dbc819/src/internal/poll/fd_windows.go#L538-L546

**Comment by codefromthecrypt** [comment]
thanks for the notes and the research leading to them!

**Comment by codefromthecrypt** [comment]
If you want to go with an alternative fix, works for me, @achille-roussel will be starting some more abstraction work soon, and the important part is to have tests in to make sure this doesn't re-break later.

**Comment by ncruces** [comment]
I'll go with this since at least it means no regression for zig folks.

The big issue is this leaving the file offset in an inconsistent state if the initial seeks succeed but the final one fails. It's still an improvement over the current situation (final offset is always wrong).

Other considerations don't really apply (`pread` is supposed to be thread-safe, but there's no concurrency in WASM). I can add some comments pointing this out.

I'll work on tests now.

**Comment by codefromthecrypt** [comment]
@ncruces sounds good. we're going to cut the release in a couple days, and this is great to go in. You can add notes in RATIONALE.md and then code comment to there on the tradeoffs. you'll notice there are others.

**Comment by codefromthecrypt** [comment]
I drifted you. for names, use export (capitalize first letter) and dot import like so `	. "github.com/tetratelabs/wazero/internal/wasi_snapshot_preview1"`

**Review by codefromthecrypt — APPROVED** [review]
great and professional work!

if you like I can fix the drift I caused.

**Comment by codefromthecrypt** [comment]
thanks for hanging in there @ncruces!

**Comment by ncruces** [comment]
No problem.
Thank you for wazero!

**Pull request merged**
