### PR TITLE
internal: add tags and stubs so wazero can be compiled for MCU targets

### PR DESCRIPTION
**Pull request by deadprogram**
This PR modifies the `internal/sock` and `internal/sysfs` packages to add tags and stubs so Wazero can be compiled for MCU targets without operating systems. This is required for bare metal targets.

related issue: https://github.com/tetratelabs/wazero/issues/1854

### CODE REVIEW

**Comment by deadprogram** [comment]
Any feedback @evacchi or @mathetake ?

**Review by achille-roussel — APPROVED** [review]
The change looks good to me. Let's wait a couple days for Edo to double check and we can merge it 👍

**Review by evacchi — APPROVED** [review]
looks ok. Let's revisit this to consolidate all the recent changes

**Comment by deadprogram** [comment]
Thanks @evacchi

**Pull request merged**
