### PR TITLE
wazevo(amd64): simd arith2 spec tests

### PR DESCRIPTION
**Pull request by evacchi**
this is based on #2004, ~~and #1997~~ for easier merging

### CODE REVIEW

**Comment by evacchi** [comment]
rebased and fixed regalloc issues

**Comment by evacchi** [comment]
rebased, added missing encoding test, fix vreg naming, allow mem args

**Comment by evacchi** [comment]
I swapped mem/reg args where appropriate to use copyToTmp(), but in some cases (unaries: abs/popcnt) I think we still need to do an explicit copy.

**Comment by evacchi** [comment]
force-push to retrigger CI which didn't run last time...

**Comment by evacchi** [comment]
(I suspect CI won't run until the PR targets main)

**Review by mathetake — APPROVED** [review]

**Pull request merged**
