### PR TITLE
wasi: non-blocking i/o on files on *nix

### PR DESCRIPTION
**Pull request by evacchi**
Addresses #1500.

We enable non-blocking I/O on files (including FIFOs); this allows [nonblock_test.go](https://github.com/golang/go/blob/5f695f7072848e425289ca94bc460da813de66da/src/runtime/internal/wasitest/nonblock_test.go) to run to completion. I am pushing here a simpler test in C, but I have tested the one in the Go tree separately. We can work at adding the same test if we want.

This is not supported on Windows (yet?) because 
1) no Mkfifo means we have to rethink the test ;) 
2) `syscall.SetNonblock()` on Windows has the following implementation :D

```go
func SetNonblock(fd Handle, nonblocking bool) (err error) {
	return nil
}
```

### CODE REVIEW

**Review by achille-roussel — APPROVED** [review]
🙌

**Review by ncruces — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
thanks @evacchi for another epic evening. When you have a chance, add to #1500 something like:

update: blah blah works
next step: copy paste notes for windows

that way it is easier to see well, what's next in the original thingy, as I'll link to it in the next release notes

**Comment by mathetake** [comment]
`imports/wasi_snapshot_preview1/example/testdata/zig-cc/cat.wasm` why in this example only the binary has been changed while the source left intact?

**Comment by codefromthecrypt** [comment]
good eye. I should have caught this. as I've noticed folks are sometimes building wasm manually or with different versions I would suggest us all look carefully and ask each other.

1. if you meant to re-build, did you use the [make targets like our examples workflow](https://github.com/tetratelabs/wazero/blob/main/.github/workflows/examples.yaml#L86-L105)?
2. if you meant to re-build, did you verify the version of the [toolchain is same as our examples workflow](https://github.com/tetratelabs/wazero/blob/main/.github/workflows/examples.yaml#L19-L21)?

**Comment by evacchi** [comment]
My bad. I rebuilt using make, without checking the version was aligned and committed all by mistake 🙏

**Pull request merged**
