### PR TITLE
Set floor Go version at 1.20

### PR DESCRIPTION
**Pull request by mathetake**

### CODE REVIEW

**Comment by mathetake** [comment]
so os package test of wasip1 failing 
```
--- FAIL: BenchmarkWasip1/baseline/Run/src_os.test
    require.go:331: expected no error, but was module closed with exit_code(1): stdout: 
        stderr: 
        /home/runner/work/wazero/wazero/internal/integration_test/stdlibs/bench_test.go:222
        /home/runner/work/wazero/wazero/internal/integration_test/stdlibs/bench_test.go:175
        /opt/hostedtoolcache/go/1.22.0/x64/src/testing/benchmark.go:193
        /opt/hostedtoolcache/go/1.22.0/x64/src/testing/benchmark.go:215
        /opt/hostedtoolcache/go/1.22.0/x64/src/runtime/asm_amd64.s:16[95](https://github.com/tetratelabs/wazero/actions/runs/7823604950/job/21344829039?pr=2025#step:6:96)
```

**Comment by evacchi** [comment]
windows is still broken though

**Comment by evacchi** [comment]
yay! it really was an issue with /tmp on Windows; best fix: fixing the CI!

**Comment by mathetake** [comment]
💯

**Pull request merged**
