### PR TITLE
Update Go cache in Pre-commit

### PR DESCRIPTION
**Pull request by mathetake**
Looks like a cache is so old that it doesn't contain any cache for goimports and golangci-lint

### CODE REVIEW

**Comment by mathetake** [comment]
let me re-kick after the first check finished

**Comment by mathetake** [comment]
### Before
Screen Shot 2021-12-31 at 10 18 07

### After
Screen Shot 2021-12-31 at 10 17 57

**Comment by mathetake** [comment]
hmm though strange that we’ve updated go.sum

**Review by codefromthecrypt — APPROVED** [review]
yes this is totally strange, but at the end of the day it is a black box we are dealing with. tainting the expression may be the only work around for now. We can try removing it later

**Pull request merged**
