### PR TITLE
site: update homepage to show CLI

### PR DESCRIPTION
**Pull request by evacchi**

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
preview URL for vetting on devices https://deploy-preview-1229--wazero.netlify.app/

**Review by codefromthecrypt — APPROVED** [review]
good job. I like it

**Comment by codefromthecrypt** [comment]
draft until RC assets uploaded (as that's what the install.sh gets)

**Review by mathetake — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
```bash
$ curl https://deploy-preview-1229--wazero.netlify.app/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9790  100  9790    0     0  15294      0 --:--:-- --:--:-- --:--:-- 15393
tetratelabs/wazero info checking GitHub for latest tag
tetratelabs/wazero info found version: 1.0.0-rc.2 for v1.0.0-rc.2/darwin/arm64
tetratelabs/wazero info installed ./bin/wazero

$  ./bin/wazero version
1.0.0-rc.2

```

**Pull request merged**
