### PR TITLE
compiler: avoid some unsafe.Pointers

### PR DESCRIPTION
**Pull request by ncruces**
These seem unneeded, so best to avoid.

### CODE REVIEW

**Review by achille-roussel — APPROVED** [review]
🔥

**Comment by ncruces** [comment]
Do we know the recent source of test failures?

**Comment by achille-roussel** [comment]
Looks like it probably was https://github.com/tetratelabs/wazero/pull/1453, weird that the tests passed in that PR 🤔 

It seems like a linter issue, one of the fields on the compiler engine isn't used anymore, do you want to address as part of this change?

**Comment by ncruces** [comment]
Fixed one of the CI failures, the other one is pretty out of scope.
Trying to address it elsewhere.

**Review by mathetake — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
I nuked the cache with the following

```bash
$ gh extension install actions/gh-actions-cache
$ gh actions-cache list
# look for stuff
$ gh actions-cache delete --confirm gojs-test-binary-1.20
```

then had to re-kick all the jobs in because the failure had a dependency, and that was easier.

**Pull request merged**
