### PR TITLE
Fix racy first instantiation

### LINKED ISSUE #929: Racy code in first module instantiation.
With 45fc45c49975fb4d8173a5bebf33e3bfe5fbb2be initial module instantiation became racy.
See output below.

**To Reproduce**

```sh
git clone --branch racy https://github.com/ncruces/wazero-bugs
cd wazero-bugs
go run -race main.go
```

**Expected behavior**

Instantiating modules is data race free.

A workaround is to instantiate the module once after compilation, and before using it:
https://github.com/ncruces/wazero-bugs/blob/8b89d6dcd79468d9908fd0fd79991a2648e7e4ff/dcraw/dcraw.go#L43-L47

**Environment (please complete the relevant information):**

Go version: go1.19.4
wazero Version: https://github.com/tetratelabs/wazero/commit/78ac85cce1d674c1c47c7ff2dacbfbc2e3a3e2b4
Host architecture: amd64
Runtime mode: compiler

**Details**

```
==================
WARNING: DATA RACE
Read at 0x00c0001fd6b0 by goroutine 15:
  github.com/tetratelabs/wazero/internal/wasm.(*FunctionType).key()
      /Users/cruces/Documents/Personal/wazero/internal/wasm/module.go:704 +0x3e
  github.com/tetratelabs/wazero/internal/wasm.(*FunctionType).String()
      /Users/cruces/Documents/Personal/wazero/internal/wasm/module.go:727 +0x64
  github.com/tetratelabs/wazero/internal/wasm.(*Store).getFunctionTypeID()
      /Users/cruces/Documents/Personal/wazero/internal/wasm/store.go:597 +0x56
  github.com/tetratelabs/wazero/internal/wasm.(*Store).getFunctionTypeIDs()
      /Users/cruces/Documents/Personal/wazero/internal/wasm/store.go:587 +0xaf
  github.com/tetratelabs/wazero/internal/wasm.(*Store).instantiate()
      /Users/cruces/Documents/Personal/wazero/internal/wasm/store.go:342 +0xaf
  github.com/tetratelabs/wazero/internal/wasm.(*Store).Instantiate()
      /Users/cruces/Documents/Personal/wazero/internal/wasm/store.go:322 +0x24e
  github.com/tetratelabs/wazero.(*namespace).InstantiateModule()
      /Users/cruces/Documents/Personal/wazero/namespace.go:82 +0x32a
  github.com/tetratelabs/wazero.(*runtime).InstantiateModule()
      /Users/cruces/Documents/Personal/wazero/runtime.go:238 +0x9c
  github.com/ncruces/wazero-bugs/dcraw.run()
      /Users/cruces/Documents/Personal/wazero-bugs/dcraw/dcraw.go:59 +0x3e8
  github.com/ncruces/wazero-bugs/dcraw.GetThumb()
      /Users/cruces/Documents/Personal/wazero-bugs/dcraw/dcraw.go:69 +0x1f9
  main.main.func1()
      /Users/cruces/Documents/Personal/wazero-bugs/main.go:18 +0x51

Previous write at 0x00c0001fd6b0 by goroutine 7:
  github.com/tetratelabs/wazero/internal/wasm.(*FunctionType).key()
      /Users/cruces/Documents/Personal/wazero/internal/wasm/module.go:721 +0x3d9
  github.com/tetratelabs/wazero/internal/wasm.(*FunctionType).String()
      /Users/cruces/Documents/Personal/wazero/internal/wasm/module.go:727 +0x64
  github.com/tetratelabs/wazero/internal/wasm.(*Store).getFunctionTypeID()
      /Users/cruces/Documents/Personal/wazero/internal/wasm/store.go:597 +0x56
  github.com/tetratelabs/wazero/internal/wasm.(*Store).getFunctionTypeIDs()
      /Users/cruces/Documents/Personal/wazero/internal/wasm/store.go:587 +0xaf
  github.com/tetratelabs/wazero/internal/wasm.(*Store).instantiate()
      /Users/cruces/Documents/Personal/wazero/internal/wasm/store.go:342 +0xaf
  github.com/tetratelabs/wazero/internal/wasm.(*Store).Instantiate()
      /Users/cruces/Documents/Personal/wazero/internal/wasm/store.go:322 +0x24e
  github.com/tetratelabs/wazero.(*namespace).InstantiateModule()
      /Users/cruces/Documents/Personal/wazero/namespace.go:82 +0x32a
  github.com/tetratelabs/wazero.(*runtime).InstantiateModule()
      /Users/cruces/Documents/Personal/wazero/runtime.go:238 +0x9c
  github.com/ncruces/wazero-bugs/dcraw.run()
      /Users/cruces/Documents/Personal/wazero-bugs/dcraw/dcraw.go:59 +0x3e8
  github.com/ncruces/wazero-bugs/dcraw.GetThumb()
      /Users/cruces/Documents/Personal/wazero-bugs/dcraw/dcraw.go:69 +0x1f9
  main.main.func1()
      /Users/cruces/Documents/Personal/wazero-bugs/main.go:18 +0x51

Goroutine 15 (running) created at:
  main.main()
      /Users/cruces/Documents/Personal/wazero-bugs/main.go:17 +0x64

Goroutine 7 (running) created at:
  main.main()
      /Users/cruces/Documents/Personal/wazero-bugs/main.go:17 +0x64
==================
Found 1 data race(s)
exit status 66
```

### PR DESCRIPTION
**Pull request by ckaznocha**
resolves #929

### CODE REVIEW

**Review by codefromthecrypt — APPROVED** [review]

**Comment by mathetake** [comment]
this makes me think that we should cache key() at binary decoding phase..

**Comment by ckaznocha** [comment]
@mathetake totally agree!

**Comment by codefromthecrypt** [comment]
> this makes me think that we should cache key() at binary decoding phase..

agreed, especially as we aren't exposing our model! someone want to do that as another change?

**Comment by codefromthecrypt** [comment]
thanks @ckaznocha and yeah interested in any further improvements as well!

**Pull request merged**
