### PR TITLE
Adds LookupFunction in experimental/table package

### PR DESCRIPTION
**Pull request by mathetake**

### CODE REVIEW

**Comment by mathetake** [comment]
PTAL @jerbob92

**Comment by jerbob92** [comment]
@mathetake Looks good to me! Shall I use this branch to change my implementation to so that we can validate it? I'm also not completely sure I always know the params/return type when I'm looking up the function, so have to try that out.

**Comment by mathetake** [comment]
Cool that sounds great! Please let me know if you have any issue

**Comment by jerbob92** [comment]
@mathetake looks like I can't reliably know the types in all cases, it is possible to move the typeID validation somewhere else or make it optional?

**Comment by mathetake** [comment]
genuine question then: how can you know the `stack` param to be passed to Call API then?

**Comment by jerbob92** [comment]
> genuine question then: how can you know the `stack` param to be passed to Call API then?

Yeah you're right, but it's pretty decoupled in embind since the setup of the invokers is in a completely different place from calling it, and it doesn't always know the types when it's setting up the invokers.

But I think I was able to work around it :)

**Comment by mathetake** [comment]
cool, keep me posted !

**Comment by jerbob92** [comment]
@mathetake Got it fully working outside the Wazero repo: https://github.com/jerbob92/wazero-emscripten-embind

So, LGTM! :+1:

**Comment by mathetake** [comment]
Awesome!

**Pull request merged**
