### PR TITLE
Delete obsolete integration test from wat parser

### PR DESCRIPTION
**Pull request by mathetake**
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

### CODE REVIEW

**Review by codefromthecrypt — COMMENTED** [review]
this shows how fast or slow our binary codec is, though. is there another reason besides wat to delete this?

**Comment by mathetake** [comment]
`EncodeModule` is not maintained anymore AFAIK plus this example `newExample()` is too unrealistic to measure the perf of decoder. I would replace it with TinyGo one and delete `newExample()` instead. on it.

**Comment by mathetake** [comment]
FYI `newExample()` is defined to line with Wat impl which is no longer existent.

**Comment by mathetake** [comment]
done

**Comment by mathetake** [comment]
@codefromthecrypt PTAL aa I don't want to fix this `TestExampleUpToDate` in #881

**Review by codefromthecrypt — APPROVED** [review]
cool I just checked and we don't use the encoder outside tests, so sounds good to me. in fact maybe we should delete the encoder.

**Comment by mathetake** [comment]
lol just in time

**Comment by codefromthecrypt** [comment]
maybe first we can move the encoder to a testing package..

**Pull request merged**
