### PR TITLE
fuzz: adds target on checking memory state

### PR DESCRIPTION
**Pull request by mathetake**
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

### CODE REVIEW

**Comment by mathetake** [comment]
now running this locally for an hour or so, and if it ends, I will make this ready

**Comment by mathetake** [comment]
seems like found a bug in memory.fill

```
Failed WebAssembly Text:
(module
  (type (;0;) (func))
  (func (;0;) (type 0)
    (local v128 f32)
    global.get 1
    i32.eqz
    if  ;; label = @1
      unreachable
    end
    global.get 1
    i32.const 1
    i32.sub
    global.set 1
    table.size 1
    table.size 0
    i32.const -1
    i32.rotr
    table.size 1
    memory.fill
  )
  (func (;1;) (type 0)
    global.get 1
    i32.eqz
    if  ;; label = @1
      unreachable
    end
    global.get 1
    i32.const 1
    i32.sub
    global.set 1
  )
  (table (;0;) 128 376 externref)
  (table (;1;) 74 241 externref)
  (memory (;0;) 1 2)
  (global (;0;) (mut funcref) ref.func 1)
  (global (;1;) (mut i32) i32.const 1000)
  (export "" (func 0))
  (export "1" (func 1))
  (export "2" (table 0))
  (export "3" (table 1))
  (export "4" (memory 0))
  (export "5" (global 0))
  (start 1)
  (elem (;0;) (table 1) (i32.const 0) externref)
)
```

**Comment by mathetake** [comment]
minimized by hand :) 

```
(module
  (type (;0;) (func))
  (func (;0;) (type 0)
    table.size 0
    table.size 0
    table.size 0
    memory.fill
  )
  (table (;1;) 1000 1000 externref)
  (memory (;0;) 1 2)
  (start 0)
)
```

**Comment by mathetake** [comment]
ok it's nothing to do with table

```
(module
  (type (;0;) (func))
  (func (;0;) (type 0)
    i32.const 1000
    i32.const 1000
    i32.const 1000
    memory.fill
  )
  (memory (;0;) 1 2)
  (start 0)
)
```

**Comment by mathetake** [comment]
extracted to #1055, and keep this draftt until we solve it

**Comment by mathetake** [comment]
good news is that it seems like there's no other bugs found

**Comment by mathetake** [comment]
so thanks to the fix by @evacchi, now 6 hours of fuzzing failed to find anything.  Marking this ready!

**Review by codefromthecrypt — APPROVED** [review]
LGTM

**Pull request merged**
