### PR TITLE
Add Memory.WriteString

### LINKED ISSUE #819: Add Memory.WriteString to avoid copying
**Is your feature request related to a problem? Please describe.**
Right now, `mem.Write(ctx, valuePtr, []byte(val))` may end up copying the string in some circumstances, which is inefficient on the calling host. Thanks to @anuraaga for noticing this.

**Describe the solution you'd like**
`mem.WriteString(ctx, valuePtr, val)` instead

**Describe alternatives you've considered**
unsafe shenanigans or assuming the compiler will be smart.

**Additional context**
https://stackoverflow.com/a/59210739
https://github.com/http-wasm/http-wasm-host-go/pull/2#discussion_r984275393

### PR DESCRIPTION
**Pull request by anuraaga**
Fixes #819

### CODE REVIEW

**Review by codefromthecrypt — APPROVED** [review]
maybe comment the bench results? I think this is handy regardless.

**Comment by anuraaga** [comment]
BTW, benchmark

```
goos: darwin
goarch: arm64
pkg: github.com/tetratelabs/wazero/internal/wasm
BenchmarkWriteString
BenchmarkWriteString/#00
BenchmarkWriteString/#00/Write
BenchmarkWriteString/#00/Write-10   	171108922	         7.016 ns/op
BenchmarkWriteString/#00/WriteString
BenchmarkWriteString/#00/WriteString-10         	474876086	         2.532 ns/op
BenchmarkWriteString/#01
BenchmarkWriteString/#01/Write
BenchmarkWriteString/#01/Write-10               	84439156	        13.57 ns/op
BenchmarkWriteString/#01/WriteString
BenchmarkWriteString/#01/WriteString-10         	421578680	         2.845 ns/op
BenchmarkWriteString/#02
BenchmarkWriteString/#02/Write
BenchmarkWriteString/#02/Write-10               	73187649	        16.17 ns/op
BenchmarkWriteString/#02/WriteString
BenchmarkWriteString/#02/WriteString-10         	442293042	         2.703 ns/op
BenchmarkWriteString/#03
BenchmarkWriteString/#03/Write
BenchmarkWriteString/#03/Write-10               	57855838	        20.49 ns/op
BenchmarkWriteString/#03/WriteString
BenchmarkWriteString/#03/WriteString-10         	378955994	         3.193 ns/op
PASS
```

Also for kicks the (not committed) version with `mem := ` instead of `api.Memory`, i.e. struct vs interface. I thought maybe struct would allow escape analysis to kick in, and it might be up to a certain length? `WriteString` is always faster but not by much, except for the long string where it is a lot. Not sure but could be a fun deep dive at some point

```
goos: darwin
goarch: arm64
pkg: github.com/tetratelabs/wazero/internal/wasm
BenchmarkWriteString
BenchmarkWriteString/#00
BenchmarkWriteString/#00/Write
BenchmarkWriteString/#00/Write-10   	376955035	         3.139 ns/op
BenchmarkWriteString/#00/WriteString
BenchmarkWriteString/#00/WriteString-10         	574923054	         2.054 ns/op
BenchmarkWriteString/#01
BenchmarkWriteString/#01/Write
BenchmarkWriteString/#01/Write-10               	315370536	         3.805 ns/op
BenchmarkWriteString/#01/WriteString
BenchmarkWriteString/#01/WriteString-10         	578792673	         2.067 ns/op
BenchmarkWriteString/#02
BenchmarkWriteString/#02/Write
BenchmarkWriteString/#02/Write-10               	361349233	         3.322 ns/op
BenchmarkWriteString/#02/WriteString
BenchmarkWriteString/#02/WriteString-10         	586718167	         2.034 ns/op
BenchmarkWriteString/#03
BenchmarkWriteString/#03/Write
BenchmarkWriteString/#03/Write-10               	60858225	        19.41 ns/op
BenchmarkWriteString/#03/WriteString
BenchmarkWriteString/#03/WriteString-10         	585787574	         2.045 ns/op
PASS
```

**Comment by codefromthecrypt** [comment]
wrt the interface vs struct. there was a plan to allow interception of memory in the future, ex tracing etc.  internally, though we can cast to the struct if it helps.

**Review by codefromthecrypt — APPROVED** [review]
cool

**Pull request merged**
