### PR TITLE
Nuke old singlepass compiler, enable optimizing compiler by default

### PR DESCRIPTION
**Pull request by mathetake**
Towards 2.0 release, this deletes the entire codebase of the old single pass
compiler. As a result, the new optimizing compiler, the code name "wazevo"
will be promoted to the default engine of wazero with this commit. The detailed
explanation will be provided with the release note, but in the meantime, you can
enjoy the compiler just by upgrading your wazero to the main branch without
changing your code base at all. 

It has been a crazy 9 months since I started writing the optimizing compiler from scratch, 
but I feel really grateful for what we have achieved for the future!

### CODE REVIEW

**Comment by mathetake** [comment]
Release workflow failures is not relevant to this PR, and will be fixed by @evacchi

**Review by achille-roussel — APPROVED** [review]
Epic work 👏

**Review by evacchi — APPROVED** [review]
💣 💥 🔥

**Review by codefromthecrypt — COMMENTED** [review]
emeritus bro-approve 👍

**Comment by ncruces** [comment]
My [branch](https://github.com/ncruces/go-sqlite3/pull/60/files) is now reduced to updating wazero. All tests [pass](https://github.com/ncruces/go-sqlite3/actions/runs/8187115886).

**Pull request merged**
