### PR TITLE
fuzz: enables threads by default

### PR DESCRIPTION
**Pull request by mathetake**
cc @anuraaga

### CODE REVIEW

**Comment by mathetake** [comment]
@anuraaga do you want to fix the bug and make the impl more solid until like 4 hours of fuzzing run without issues?

**Comment by anuraaga** [comment]
Fuzzing is indeed the best, that's really cool. I can fix the bug, but if you're asking if I can run a 4 hour fuzz, I don't have a always-on separate computer. I can see if the fuzz command in the background doesn't kill my Mac while doing normal work.

**Comment by mathetake** [comment]
> I can see if the fuzz command in the background doesn't kill my Mac while doing normal work.

yeah usually running 2 or 4 jobs on m1 mac while doing other work could be possible (I am doing that alot)

**Comment by mathetake** [comment]
also I would appreciate it if you could go ahead and fix the bug

**Comment by mathetake** [comment]
ok now at least minimal fuzzing job (3m per target) passing

**Pull request merged**
