### PR TITLE
Bulk memory binary encoding and validation

### PR DESCRIPTION
**Pull request by mathetake**
part of #321

### CODE REVIEW

**Comment by mathetake** [comment]
ok the left is data count section

**Comment by mathetake** [comment]
OK finished the encoding and validation.. in anyway the feature flag is not exposed in the public API so it is fine to land main branch without having actual compiler impl

**Comment by mathetake** [comment]
again waiting for @codefromthecrypt to do spectest refactoring 😄

**Comment by mathetake** [comment]
rebased.. will continue the encoding in the text compiler then will mark this ready

**Comment by codefromthecrypt** [comment]
taking this on for a bit :D

**Pull request merged**
