### PR TITLE
build: go 1.16 support by adding +build comments alongside go:build ones

### PR DESCRIPTION
**Pull request by bobby-stripe**
I believe this is the way to enable both go1.16 and go1.17+ support.

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
I rebased this since main drifted a bit

**Review by mathetake — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
Thanks for the help @bobby-stripe!

**Comment by codefromthecrypt** [comment]
#46 adds CI for go 1.16. A later PR will reduce build flags to reduce compilation drift.

**Comment by bobby-stripe** [comment]
thanks for merging this!

**Comment by codefromthecrypt** [comment]
analysis on pros and cons of the last remaining build flag https://github.com/tetratelabs/wazero/pull/52

**Comment by bobby-stripe** [comment]
@codefromthecrypt yup! we are

**Comment by bobby-stripe** [comment]
happy to have this rolled back if its a burden

**Comment by codefromthecrypt** [comment]
mainly we are thinking about how to handle trailing versions, as 1.18 is coming soon! I might preemptively roll back 1.16 and see if anyone else screams 😎 thanks for the feedback!

**Comment by codefromthecrypt** [comment]
before I pull the trigger on removing 1.16.. @pkedy @pims @cretz @wuhuizuo @wdvxdr1123 can you mention if you require 1.16 and/or how close you are to needing 1.18? Currently, we don't test with 1.18 betas. It would be convenient to only test two versions of go, when it comes out (1.17 and 1.18).

**Comment by pims** [comment]
I’m using 1.17 and no immediate plan to upgrade to 1.18.

**Comment by codefromthecrypt** [comment]
I think @pkedy is busy, but considering dapr set floor level to go 1.17 I think we should be able to proceed. there are a lot of perf advantages to this.

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/wazero/pull/317 will move to floor 1.17

**Pull request merged**
