### PR TITLE
cli: adds -hostlogging=filesystem for diagnosing problems

### PR DESCRIPTION
**Pull request by codefromthecrypt**
This adds a logging flag with only one initial option: filesystem

This is needed to complete filesystem support in WASI and `GOARCH=wasm GOOS=js`. This PR is rough, but the code will  be improved over the week alongside filesystem improvements.

### Example of TinyGo (WASI) tests

*NOTE: the test itself is expected to fail. What's visible here is what filesystem calls led to the failure*
```bash
$ ./build/tinygo test -target wasi -c -o os.wasm os
$ wazero run -hostlogging=filesystem -mount=.:/ os.wasm -test.v
==> wasi_snapshot_preview1.fd_prestat_get(fd=3)
<== (prestat={pr_name_len=1},errno=ESUCCESS)
==> wasi_snapshot_preview1.fd_prestat_dir_name(fd=3)
<== (path=/,errno=ESUCCESS)
==> wasi_snapshot_preview1.fd_prestat_get(fd=4)
<== (prestat=,errno=EBADF)
--> wasi_snapshot_preview1.path_unlink_file(fd=3,path=tmp/_os_test_TestTempDir)
<-- errno=ENOSYS
--> wasi_snapshot_preview1.path_remove_directory(fd=3,path=tmp/_os_test_TestTempDir)
<-- errno=ENOSYS
==> wasi_snapshot_preview1.fd_fdstat_get(fd=3)
<== (stat={filetype=DIRECTORY,fdflags=APPEND,fs_rights_base=,fs_rights_inheriting=},errno=ESUCCESS)
==> wasi_snapshot_preview1.path_open(fd=3,dirflags=SYMLINK_FOLLOW,path=tmp/_os_test_TestTempDir,oflags=CREAT,fs_rights_base=,fs_rights_inheriting=,fdflags=)
<== (opened_fd=,errno=ENOENT)
--> wasi_snapshot_preview1.path_unlink_file(fd=3,path=_os_test_TestChDir)
<-- errno=ENOSYS
--> wasi_snapshot_preview1.path_remove_directory(fd=3,path=_os_test_TestChDir)
<-- errno=ENOSYS
--> wasi_snapshot_preview1.path_create_directory(fd=3,path=_os_test_TestChDir)
<-- errno=ENOSYS
==> wasi_snapshot_preview1.path_filestat_get(fd=3,flags=SYMLINK_FOLLOW,path=_os_test_TestChDir)
<== (filestat=,errno=ENOENT)
--> wasi_snapshot_preview1.path_unlink_file(fd=3,path=_os_test_TestChDir)
<-- errno=ENOSYS
--> wasi_snapshot_preview1.path_remove_directory(fd=3,path=_os_test_TestChDir)
<-- errno=ENOSYS
==> wasi_snapshot_preview1.fd_fdstat_get(fd=3)
<== (stat={filetype=DIRECTORY,fdflags=APPEND,fs_rights_base=,fs_rights_inheriting=},errno=ESUCCESS)
==> wasi_snapshot_preview1.path_open(fd=3,dirflags=SYMLINK_FOLLOW,path=tmp/TestFd.txt614390,oflags=CREAT|EXCL,fs_rights_base=,fs_rights_inheriting=,fdflags=)
<== (opened_fd=,errno=ENOENT)
==> wasi_snapshot_preview1.fd_write(fd=1,iovs=93508,iovs_len=1)
panic: runtime error: nil pointer dereference
<== (nwritten=46,errno=ESUCCESS)
error instantiating wasm binary: module[] function[_start] failed: wasm error: unreachable
wasm stack trace:
	.runtime.runtimePanic(i32,i32)
		0x9541: /Users/adrian/oss/tinygo/src/runtime/runtime_tinygowasm.go:72:6 (inlined)
		        /Users/adrian/oss/tinygo/src/runtime/panic.go:59:7
	.runtime.nilPanic()
		0x5d7f: /Users/adrian/oss/tinygo/src/runtime/panic.go:122:14 (inlined)
		        /Users/adrian/oss/tinygo/src/runtime/gc_stack_portable.go:46:21
	.(*os.File).Name(i32,i32)
		0x3452d: /Users/adrian/oss/tinygo/src/os/file.go:71:2 (inlined)
		         <Go interface method> (inlined)
--snip--
```

### Example of `GOARCH=wasm GOOS=js` tests
*NOTE: the test itself is expected to fail. What's visible here is what filesystem calls led to the failure*

```bash
$ GOARCH=wasm GOOS=js ./bin/go test -c -o os.wasm os
$ ../wazero/wazero run -hostlogging=filesystem -mount=.:/ os.wasm -test.v
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=21,fOffset=<nil>))
=== RUN   TestExpand
<== (err=<nil>,n=21)
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=29,fOffset=<nil>))
--- PASS: TestExpand (0.00s)
<== (err=<nil>,n=29)
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=32,fOffset=<nil>))
=== RUN   TestConsistentEnviron
<== (err=<nil>,n=32)
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=40,fOffset=<nil>))
--- PASS: TestConsistentEnviron (0.00s)
<== (err=<nil>,n=40)
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=23,fOffset=<nil>))
=== RUN   TestUnsetenv
<== (err=<nil>,n=23)
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=31,fOffset=<nil>))
--- PASS: TestUnsetenv (0.00s)
<== (err=<nil>,n=31)
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=23,fOffset=<nil>))
=== RUN   TestClearenv
<== (err=<nil>,n=23)
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=31,fOffset=<nil>))
--- PASS: TestClearenv (0.00s)
<== (err=<nil>,n=31)
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=24,fOffset=<nil>))
=== RUN   TestLookupEnv
<== (err=<nil>,n=24)
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=32,fOffset=<nil>))
--- PASS: TestLookupEnv (0.00s)
<== (err=<nil>,n=32)
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=33,fOffset=<nil>))
=== RUN   TestEnvironConsistency
<== (err=<nil>,n=33)
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=41,fOffset=<nil>))
--- PASS: TestEnvironConsistency (0.00s)
<== (err=<nil>,n=41)
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=25,fOffset=<nil>))
=== RUN   TestErrIsExist
<== (err=<nil>,n=25)
==> go.syscall/js.valueCall(fs.open(name=/tmp/_Go_ErrIsExist3171997792,flags=,perm=-rw-------))
<== (err=open tmp/_Go_ErrIsExist3171997792: file does not exist,fd=0)
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=110,fOffset=<nil>))
    error_test.go:19: open ErrIsExist tempfile: open /tmp/_Go_ErrIsExist3171997792: No such file or directory
<== (err=<nil>,n=110)
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=33,fOffset=<nil>))
--- FAIL: TestErrIsExist (0.00s)
<== (err=<nil>,n=33)
==> go.syscall/js.valueCall(fs.write(fd=1,offset=0,byteCount=28,fOffset=<nil>))
=== RUN   TestErrIsNotExist
<== (err=<nil>,n=28)
error instantiating wasm binary: runtime error: invalid memory address or nil pointer dereference (recovered by wazero)
wasm stack trace:
	go.syscall/js.valueCall(i32)
	.syscall_js.valueCall(i32) i32
	.syscall_js.Value.Call(i32) i32
	.syscall.fsCall(i32) i32
	.syscall.Mkdir(i32) i32
	.os.Mkdir.func1(i32) i32
	.os.Mkdir(i32) i32
	.os.MkdirTemp(i32) i32
	.wasm_pc_f_loop()
	.wasm_export_run(i32,i32)
```

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
funny this test found that mtimeMs was broken due to precision problem. fixed it.

**Review by mathetake — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
dates are correct now, just the test will fail since we aren't checking out full history (has mtime of now instead of real mtime). I'll change the test with a comment.

**Comment by codefromthecrypt** [comment]
windows flags don't match. will sort it in the morning

**Comment by codefromthecrypt** [comment]
ok finished all flags and refreshed desc. This will help a lot as we implement create/mkdir support.

waiting until tests pass in case there's a remaining windows issue.

**Comment by codefromthecrypt** [comment]
windows issue is that it hasn't a world perms thing, and the string logging of stat helped identify it. should be sorted now.

**Pull request merged**
