### PR TITLE
Merge wazero-fuzz into internal/integration_test

### PR DESCRIPTION
**Pull request by mathetake**
To make it easy for anyone interested to run fuzzing, not only myself, this merges the code in https://github.com/tetratelabs/wazero-fuzz repository into integration tests.

Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

### CODE REVIEW

**Comment by mathetake** [comment]
lol actually find the bug :D

**Comment by mathetake** [comment]
```
Failed WebAssembly Text:
(module
  (table (;0;) 34 553 externref)
  (global (;0;) (mut i32) i32.const 1000)
  (export "" (table 0))
  (elem (;0;) (i32.const -1) externref (ref.null extern) (ref.null extern))
)

Failed Wasm binary has been written to /home/runner/work/wazero/wazero/internal/integration_test/fuzz/wazerolib/testdata/ea73d5e64fa46742f9ee7a88c08632fc66f01277dc27208190a3ccb4ebba2677.wasm
Failed Wasm Text has been written to /home/runner/work/wazero/wazero/internal/integration_test/fuzz/wazerolib/testdata/ea73d5e64fa46742f9ee7a88c08632fc66f01277dc27208190a3ccb4ebba2677.wat
To reproduce the failure, execute: WASM_BINARY_PATH=/home/runner/work/wazero/wazero/internal/integration_test/fuzz/wazerolib/testdata/ea73d5e64fa46742f9ee7a88c08632fc66f01277dc27208190a3ccb4ebba2677.wasm go test wazerolib/...
```

**Comment by mathetake** [comment]
Ok cool caching works now... will add more docs and write test for tests :D 
image

**Comment by mathetake** [comment]
rebased onto https://github.com/tetratelabs/wazero/pull/874, will rebase onto main after merge https://github.com/tetratelabs/wazero/pull/874

**Comment by mathetake** [comment]
cool back to normal (running 1 hour fuzzing on my local m1)
```
###### End of recommended dictionary. ######
Done 2941729 runs in 3601 second(s)
```

**Review by codefromthecrypt — APPROVED** [review]
Excellent. we had been doing this ad-hoc per release and now we at least automate minimal!

**Pull request merged**
