### PR TITLE
cli: adds version command

### PR DESCRIPTION
**Pull request by mathetake**
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

### CODE REVIEW

**Comment by mathetake** [comment]
this simply prints "dev" all the time.. need a way to embed version

**Comment by mathetake** [comment]
maybe release a binary on the GitHub release where we embed the version

**Comment by mathetake** [comment]
so `go install` doesn't work if there's replace in it. hmm

**Comment by mathetake** [comment]
https://github.com/tetratelabs/wazero/pull/950/commits/c9956f8413c31c5766024a1a759d35060aad991c is the possible solution, but it doesn't compile on 1.17. 😞

**Comment by mathetake** [comment]
cool working now

```
$ go install github.com/tetratelabs/wazero/cmd/wazero@cmdversion                              
go: downloading github.com/tetratelabs/wazero v1.0.0-pre.5.0.20221221043430-4363e52ee18b

$ wazero version
v1.0.0-pre.5.0.20221221043430-4363e52ee18b
```

**Review by codefromthecrypt — APPROVED** [review]
good I was looking for this yesterday!

**Pull request merged**
